#!/usr/bin/env bash
### BEGIN INIT INFO
# Provides:          pt-kill
# Required-Start:    $network $named $remote_fs $syslog
# Required-Stop:     $network $named $remote_fs $syslog
# Should-Start:      pt-stalk
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO                                                                                                                                          

# HOME=/root need for service can find /root/.my.cnf
export HOME=/root

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME="pt-kill"
DESC="pt-kill"
DAEMON="/usr/bin/$NAME"
PIDFILE="/var/run/${NAME}.pid"
CONFIGFILE="/etc/percona-toolkit/${NAME}.conf"
[ -r /etc/default/$NAME ] && . /etc/default/$NAME
DAEMON_OPTS="--config $CONFIGFILE --daemonize --pid $PIDFILE"

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

sig () {
    test -s "$PIDFILE" && kill -$1 `cat $PIDFILE`
}

start() {
	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON \
        --test > /dev/null \
		|| return 1
	#start-stop-daemon --start --quiet --make-pidfile --pidfile $PIDFILE \
	start-stop-daemon --start --quiet --pidfile $PIDFILE \
        --exec $DAEMON -- \
		$DAEMON_OPTS \
		|| return 2
}

stop() {
	start-stop-daemon --stop --quiet --pidfile $PIDFILE
	RETVAL="$?"
	[ "$RETVAL" = 2 ] && return 2
	start-stop-daemon --stop --quiet --oknodo --exec $DAEMON
	[ "$?" = 2 ] && return 2
	# Many daemons don't delete their pidfiles when they exit.
	rm -f $PIDFILE
	return "$RETVAL"
}

status() {
  if sig 0 ; then
    echo "$DESC (`cat $PIDFILE`) is running."
    return 0
  else
    echo "$DESC is stopped."
    return 1
  fi
}

case "$1" in
  start)
    log_begin_msg "Starting $DESC"
  	start
  	log_end_msg $?
  	;;

  stop)
  	log_begin_msg "Stopping $DESC"
  	stop
  	log_end_msg $?
  	;;
  status)
    status ;;

  restart)
    log_begin_msg "Restarting $DESC"
    stop
    sleep 1
    start
    log_end_msg $?
    ;;

  *)
    echo "Usage: $0 {start|stop|status|}" >&2
    exit 1
    ;;
esac
